# used for developement when application is run with dev profile
server:
    port: 8082
    address: localhost

https:
    port: 8445

mongodb:
  url: localhost:27017
  databaseName: mica
  username:
  password:
  authSource:
  options:

opal:
  url: https://localhost:8443
  username: administrator
  password: password

agate:
  url: https://localhost:8444
  application:
    name: mica
    key: changeit

elasticsearch:
  dataNode: true
  clusterName: mica
  shards: 5
  replicas: 1
  settings: "http.enabled: true"
  maxConcurrentJoinQueries: 2
  concurrentJoinQueriesWaitTimeout: 15000

shiro:
  password:
    nbHashIterations: 10000
    salt: mica

#
# Other advanced settings
#

spring:
  profiles: dev
  thymeleaf:
    mode: XHTML
    cache: false
  mail:
    host: localhost
    port: 25
    user:
    password:
    protocol: smtp
    tls: false
    auth: false
  messageSource:
    cacheSeconds: 1


metrics:
    jmx.enabled: true
    graphite:
        enabled: false
        host: localhost
        port: 2003

cache:
    timeToLiveSeconds: 3600

# You can add as many as folders to watch
# You just need to add a dash + the directory to watch
hotReload:
    enabled: true
    package:
      project: org.obiba.mica
      domain: org.obiba.mica.domain
      restdto: org.obiba.mica.web.rest.dto
    watchdir:
      - target/classes

# Disable Jolokia - An http/json bridge for remote JMX access
endpoints.jolokia.enabled: false

async:
    corePoolSize: 10
    maxPoolSize: 50
    queueCapacity: 1000
    opal:
      corePoolSize: 10
      maxPoolSize: 50
      queueCapacity: 1000
